In [4]:
#Hej Jacob, kør denne celle
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
from urllib.parse import unquote, quote
import scraping_class
from tqdm import tqdm_notebook

In [2]:

#Building blocks
#row = ["Kursus","Fakultet", "Institut","Termin","ECTS","Eksamenstype","Antal tilmeldte",\
#        "Fremmødte", "Antal bestået", "Eksamensgennemsnit",12,10,7,4,2,0,-3,\
#        "Ej mødt","Ikke bestået"]
#df = pd.DataFrame(row)

#What do you want to scrape?
#base_url = "http://karakterstatistik.stads.ku.dk/Histogram/AØKB08003E/"
#sem = ["Winter-2014","Summer-2015","Winter-2015","Summer-2016","Winter-2016","Summer-2017","Winter-2017","Summer-2018","Winter-2018","Summer-2019"]

#Try the hard scrape:
#urls = "http://karakterstatistik.stads.ku.dk/Histogram/NFYK14019E/Summer-2015/B3http://karakterstatistik.stads.ku.dk/Histogram/SFAK18001E/Winter-2018/B1http://karakterstatistik.stads.ku.dk/Histogram/TTEABAF15E/Summer-2018http://karakterstatistik.stads.ku.dk/Histogram/TTEABAF15E/Winter-2016http://karakterstatistik.stads.ku.dk/Histogram/TTEABAF15E/Summer-2016http://karakterstatistik.stads.ku.dk/Histogram/TTEABAF15E/Summer-2015http://karakterstatistik.stads.ku.dk/Histogram/TTEABAF15E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/TTEAKAF30E/Winter-2015http://karakterstatistik.stads.ku.dk/Histogram/TTEAKAF30E/Summer-2015http://karakterstatistik.stads.ku.dk/Histogram/TTEAKAF30E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/TTEAKAF30E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/ASTB12435E/Summer-2018http://karakterstatistik.stads.ku.dk/Histogram/ASTB12435E/Winter-2016http://karakterstatistik.stads.ku.dk/Histogram/ASTK15435E/Summer-2018http://karakterstatistik.stads.ku.dk/Histogram/ASTK15435E/Winter-2016http://karakterstatistik.stads.ku.dk/Histogram/ASTK15339E/Winter-2015http://karakterstatistik.stads.ku.dk/Histogram/ASTK12339E/Winter-2015http://karakterstatistik.stads.ku.dk/Histogram/ASTB12339E/Winter-2015http://karakterstatistik.stads.ku.dk/Histogram/ASTB12250E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/ASTK12250E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/ASTK18206E/Summer-2019http://karakterstatistik.stads.ku.dk/Histogram/ASTB12206E/Summer-2019http://karakterstatistik.stads.ku.dk/Histogram/NNMK14003E/Summer-2015/B4http://karakterstatistik.stads.ku.dk/Histogram/NNMK14003E/Winter-2014/B2http://karakterstatistik.stads.ku.dk/Histogram/NNMK14004E/Summer-2015/B3http://karakterstatistik.stads.ku.dk/Histogram/NNMK14004E/Winter-2014/B1http://karakterstatistik.stads.ku.dk/Histogram/LSLS10093E/Summer-2018/B5http://karakterstatistik.stads.ku.dk/Histogram/LSLS10093E/Summer-2017/B5http://karakterstatistik.stads.ku.dk/Histogram/LSLS10093E/Summer-2016/B5http://karakterstatistik.stads.ku.dk/Histogram/LSLS10093E/Summer-2015/B5http://karakterstatistik.stads.ku.dk/Histogram/LSLS10093E/Summer-2014/B5http://karakterstatistik.stads.ku.dk/Histogram/SFOA09009E/Summer-2019http://karakterstatistik.stads.ku.dk/Histogram/SFOA09009E/Summer-2018http://karakterstatistik.stads.ku.dk/Histogram/SFOA09009E/Summer-2017http://karakterstatistik.stads.ku.dk/Histogram/SFOA09009E/Summer-2016http://karakterstatistik.stads.ku.dk/Histogram/SFOA09009E/Summer-2015http://karakterstatistik.stads.ku.dk/Histogram/SFOA09009E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/HKMB10051E/Summer-2019http://karakterstatistik.stads.ku.dk/Histogram/HKMB10051E/Summer-2018http://karakterstatistik.stads.ku.dk/Histogram/HKMB10051E/Summer-2017http://karakterstatistik.stads.ku.dk/Histogram/HKMB10051E/Summer-2016http://karakterstatistik.stads.ku.dk/Histogram/HKMB10051E/Summer-2015http://karakterstatistik.stads.ku.dk/Histogram/HKMB00172E/Summer-2019http://karakterstatistik.stads.ku.dk/Histogram/HKMB00172E/Summer-2018http://karakterstatistik.stads.ku.dk/Histogram/HKMB00172E/Summer-2017http://karakterstatistik.stads.ku.dk/Histogram/HKMB00172E/Summer-2016http://karakterstatistik.stads.ku.dk/Histogram/HKMB00172E/Summer-2015http://karakterstatistik.stads.ku.dk/Histogram/HFKB03617E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/HINK03131E/Summer-2018http://karakterstatistik.stads.ku.dk/Histogram/HINK03131E/Summer-2017http://karakterstatistik.stads.ku.dk/Histogram/HINK03131E/Summer-2016http://karakterstatistik.stads.ku.dk/Histogram/HINK03131E/Winter-2015http://karakterstatistik.stads.ku.dk/Histogram/HINK03131E/Summer-2015http://karakterstatistik.stads.ku.dk/Histogram/HINK03131E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/HINK03131E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/HFIK03461E/Summer-2015http://karakterstatistik.stads.ku.dk/Histogram/HFIB00381E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/HFIB00381E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/HMMK03011E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/HMMK03061E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/HHIK03171E/Summer-2015http://karakterstatistik.stads.ku.dk/Histogram/HHIK03171E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/HKGK03421E/Summer-2016http://karakterstatistik.stads.ku.dk/Histogram/HDAK03501E/Winter-2017http://karakterstatistik.stads.ku.dk/Histogram/HOLK03991E/Summer-2015http://karakterstatistik.stads.ku.dk/Histogram/HLKA04091E/Summer-2015http://karakterstatistik.stads.ku.dk/Histogram/HMKA04011E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/HMKA04021E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/HMKA04031E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/HMKA04041E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/HDCB00051E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/HPÆA05101E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/HTEA05101E/Summer-2016http://karakterstatistik.stads.ku.dk/Histogram/HDCB00061E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/HDCB00071E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/HDCB00081E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/HDCB00101E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/HDCB00111E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/HDCB00091E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/NFYK14008E/Winter-2015/B2http://karakterstatistik.stads.ku.dk/Histogram/NFYK14008E/Winter-2014/B2http://karakterstatistik.stads.ku.dk/Histogram/HENB10521E/Summer-2019http://karakterstatistik.stads.ku.dk/Histogram/HENB10521E/Winter-2018http://karakterstatistik.stads.ku.dk/Histogram/HENB10521E/Summer-2018http://karakterstatistik.stads.ku.dk/Histogram/HENB10521E/Winter-2017http://karakterstatistik.stads.ku.dk/Histogram/HENB10521E/Summer-2017http://karakterstatistik.stads.ku.dk/Histogram/HENB10521E/Winter-2016http://karakterstatistik.stads.ku.dk/Histogram/HENB10521E/Summer-2016http://karakterstatistik.stads.ku.dk/Histogram/HENB10521E/Winter-2015http://karakterstatistik.stads.ku.dk/Histogram/HENB10521E/Summer-2015http://karakterstatistik.stads.ku.dk/Histogram/HENB10521E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/HENB10521E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/AGDK14010E/Summer-2019http://karakterstatistik.stads.ku.dk/Histogram/AGDK14010E/Winter-2018http://karakterstatistik.stads.ku.dk/Histogram/AGDK14010E/Summer-2018http://karakterstatistik.stads.ku.dk/Histogram/AGDK14010E/Winter-2017http://karakterstatistik.stads.ku.dk/Histogram/AGDK14010E/Summer-2017http://karakterstatistik.stads.ku.dk/Histogram/AGDK14010E/Winter-2016http://karakterstatistik.stads.ku.dk/Histogram/AGDK14010E/Summer-2016http://karakterstatistik.stads.ku.dk/Histogram/AGDK14010E/Winter-2015http://karakterstatistik.stads.ku.dk/Histogram/HIOK03641E/Summer-2019http://karakterstatistik.stads.ku.dk/Histogram/HIOK03641E/Winter-2018http://karakterstatistik.stads.ku.dk/Histogram/HIOK03641E/Winter-2017http://karakterstatistik.stads.ku.dk/Histogram/HIOK03641E/Winter-2016http://karakterstatistik.stads.ku.dk/Histogram/HNAK03471E/Summer-2019http://karakterstatistik.stads.ku.dk/Histogram/HNAK03471E/Winter-2017http://karakterstatistik.stads.ku.dk/Histogram/HNAK03471E/Winter-2016http://karakterstatistik.stads.ku.dk/Histogram/HNAK03471E/Summer-2016http://karakterstatistik.stads.ku.dk/Histogram/HNAK03471E/Summer-2015http://karakterstatistik.stads.ku.dk/Histogram/HNAK03471E/Winter-2014http://karakterstatistik.stads.ku.dk/Histogram/HNAK03471E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/HÆGK03471E/Winter-2017http://karakterstatistik.stads.ku.dk/Histogram/HÆGK03471E/Summer-2016http://karakterstatistik.stads.ku.dk/Histogram/HÆGK03471E/Summer-2015http://karakterstatistik.stads.ku.dk/Histogram/HÆGK03471E/Summer-2014http://karakterstatistik.stads.ku.dk/Histogram/HASK03471E/Summer-2017http://karakterstatistik.stads.ku.dk/Histogram/HCCK03191E/Summer-2016http://karakterstatistik.stads.ku.dk/Histogram/HCCK03191E/Winter-2015"
#urls = urls.split("http")
#for i in range(0,len(urls)):
#    urls[i] = "http"+urls[i]
#urls = urls[1:120]
#urls.append("http://karakterstatistik.stads.ku.dk/Histogram/AØKB08003E/Winter-2014")
#urls.append("http://karakterstatistik.stads.ku.dk/Histogram/AØKB08003E/Summer-2015")
#len(urls)

In [6]:
#base_url = "http://karakterstatistik.stads.ku.dk/Histogram/AØKB08003E/"
#sem = ["Winter-2014","Summer-2015","Winter-2015","Summer-2016","Winter-2016","Summer-2017","Winter-2017","Summer-2018","Winter-2018","Summer-2019"]

In [10]:

#What columns do you want to inspect?
#infile_1 = df.iloc[:180:190]
#infile_1

,0,1,re 1,2,re 2,3,re 3,4,re 4,5,...,116,re 116,117,re 117,118,re 118,119,re 119,120,re 120
0,Kursus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
#base_url = "http://karakterstatistik.stads.ku.dk/Histogram/AØKB08003E/"
#sem = ["Winter-2014","Summer-2015","Winter-2015","Summer-2016","Winter-2016","Summer-2017","Winter-2017","Summer-2018","Winter-2018","Summer-2019"]
#Building blocks
#row = ["Kursus","Fakultet", "Institut","Termin","ECTS","Eksamenstype","Antal tilmeldte",\
#        "Fremmødte", "Antal bestået", "Eksamensgennemsnit",12,10,7,4,2,0,-3,\
#        "Ej mødt","Ikke bestået"]
#df = pd.DataFrame(row)

#urls = ["http://karakterstatistik.stads.ku.dk/Histogram/AØKA08178E/Summer-2018/B5",\
#       "http://karakterstatistik.stads.ku.dk/Histogram/AØKA08178E/Summer-2017/B5",\
#       "http://karakterstatistik.stads.ku.dk/Histogram/AØKB08003E/Summer-2017"]
#for i in range(0,len(urls)):
#    print(urls[i])

http://karakterstatistik.stads.ku.dk/Histogram/AØKA08178E/Summer-2018/B5
http://karakterstatistik.stads.ku.dk/Histogram/AØKA08178E/Summer-2017/B5
http://karakterstatistik.stads.ku.dk/Histogram/AØKB08003E/Summer-2017

In [5]:
#KØR DENNE CELLE!
#KØR DENNE CELLE!

# FRA JACOBs program
list_of_grade_urls = []
url = "http://karakterstatistik.stads.ku.dk/Search/Courses"
for i in range(95):
    data = {
        "searchText": "", 
        "term": "", 
        "block": "", 
        "faculty": "",
        "institute": "null",
        "page": i,
        }
    response = requests.post(url, data=data)
    html = response.text
    soup = BeautifulSoup(html)
    links = soup.findAll('a')
    list_of_grade_urls.extend([link['href'] for link in links if link.has_attr('href')])

list_of_grade_urls
for i in range(len(list_of_grade_urls)):
    list_of_grade_urls[i] = unquote(list_of_grade_urls[i])

row = ["URL","Kursus","Fakultet", "Institut","Termin","ECTS","Eksamenstype","Antal tilmeldte",\
        "Fremmødte", "Antal bestået", "Eksamensgennemsnit",12,10,7,4,2,0,-3,\
        "Ej mødt","Ikke bestået"]
df = pd.DataFrame(row)

import scraping_class
logfile = 'logPhilip.txt' ## name your log file.
connector = scraping_class.Connector(logfile)

In [6]:
# DETTE ER SCRAPER, SÅ DENNE SKAL KØRES.
errormessages = []
faultyurls = []
urls = list_of_grade_urls
for j in tqdm_notebook(range(0,len(urls))):
    
    #url = base_url + sem[j]
    url = urls[j]
    s = connector.get(url,"grade_scrape")
    s_new = s[0].text
    s = BeautifulSoup(s_new)
    x0 = (str(s.findAll("h2"))[7:])[:-6]
    
    #IDENTIFY WEBSITE AND SCRAPE
    #print(url)
    try:
        dff = pd.read_html(quote(url, safe=':/'),encoding='utf-8')
    
        #SOFT RESULTS
        keys = []
        values = []

        for i in range(0,len(dff[0][0])):
            keys.append(dff[0][0][i])
            values.append(dff[0][1][i])
        dictionary = dict(zip(keys,values))

        if "Fakultet" in dictionary:
            x1 = dictionary["Fakultet"]
        else:
            x1 = np.nan
        if "Institut" in dictionary:
            x2 = dictionary["Institut"]
        else:
            x2 = np.nan
        if "Termin" in dictionary:
            x3 = dictionary["Termin"]
        else:
            x3 = np.nan
        if "ECTS" in dictionary:
            x4 = dictionary["ECTS"]
        else:
            x4 = np.nan
        if "Ordinær eksamen" in dictionary:
            x5 = dictionary["Ordinær eksamen"]
        else:
            x5 = np.nan
        if "Antal tilmeldte" in dictionary:
            x6 = dictionary["Antal tilmeldte"]
        else:
            x6 = np.nan
        if "Fremmødte" in dictionary:
            x7 = dictionary["Fremmødte"]
        else:
            x7 = np.nan

        #data1 = [x0,x1,x2,x3,x4,x5,x6,x7]
    
        #HARD RESULTS
        if len(dff) >= 4:
            Karakter = []
            Antal = []
            for i in range(0,len(dff[2]["Karakter"])):
                Karakter.append(dff[2]["Karakter"][i])
                Antal.append(dff[2]["Antal"][i])
            dictionary = dict(zip(Karakter,Antal))
            #print(dictionary)
            Beståetlist = []
    
            tolv = 12
            ti = 10
            syv = 7
            fire = 4
            nulto = 2
            nulnul = 0
            minustre = -3

            newkeys = []
            newvalues = []
            if "12" in dictionary:
                newkeys.append(tolv)
                newvalues.append(dictionary["12"])
                Beståetlist.append(dictionary["12"])
                x_12 = dictionary["12"]
            elif 12 in dictionary:
                newkeys.append(tolv)
                newvalues.append(dictionary[12])
                Beståetlist.append(dictionary[12])
                x_12 = dictionary[12]
            else:
                x_12 = np.nan
            if "10" in dictionary:
                newkeys.append(ti)
                newvalues.append(dictionary["10"])
                Beståetlist.append(dictionary["10"])
                x_10 = dictionary["10"]
            elif 10 in dictionary:
                newkeys.append(ti)
                newvalues.append(dictionary[10])
                Beståetlist.append(dictionary[10])
                x_10 = dictionary[10]
            else:
                x_10 = np.nan
            if "7" in dictionary:
                newkeys.append(syv)
                newvalues.append(dictionary["7"])
                Beståetlist.append(dictionary["7"])
                x_7 = dictionary["7"]
            elif 7 in dictionary:
                newkeys.append(syv)
                newvalues.append(dictionary[7])
                Beståetlist.append(dictionary[7])
                x_7 = dictionary[7]
            else:
                x_7 = np.nan
            if "4" in dictionary:
                newkeys.append(fire)
                newvalues.append(dictionary["4"])
                Beståetlist.append(dictionary["4"])
                x_4 = dictionary["4"]
            elif 4 in dictionary:
                newkeys.append(fire)
                newvalues.append(dictionary[4])
                Beståetlist.append(dictionary[4])
                x_4 = dictionary[4]
            else:
                x_4 = np.nan
            if "02" in dictionary:
                newkeys.append(nulto)
                newvalues.append(dictionary["02"])
                Beståetlist.append(dictionary["02"])
                x_02 = dictionary["02"]
            elif 2 in dictionary:
                newkeys.append(nulto)
                newvalues.append(dictionary[2])
                Beståetlist.append(dictionary[2])
                x_02 = dictionary[2]
            else:
                x_02 = np.nan
            if "00" in dictionary:
                newkeys.append(nulnul)
                newvalues.append(dictionary["00"])
                x_00 = dictionary["00"]
            elif 0 in dictionary:
                newkeys.append(nulnul)
                newvalues.append(dictionary[0])
                x_00 = dictionary[0]
            else:
                x_00 = np.nan
            if "-3" in dictionary:
                newkeys.append(minustre)
                newvalues.append(dictionary["-3"]) 
                x_m3 = dictionary["-3"]
            elif -3 in dictionary:
                newkeys.append(minustre)
                newvalues.append(dictionary[-3]) 
                x_m3 = dictionary[-3]
            else:
                x_m3 = np.nan
            if "Ej mødt" in dictionary:
                Ejmødt = dictionary["Ej mødt"]
            else:
                Ejmødt = np.nan
            if "Ikke bestået" in dictionary:
                Ikkebestået = dictionary["Ikke bestået"]
            else:
                Ikkebestået = np.nan
            if "Bestået" in dictionary:
                Bestået = dictionary["Bestået"]
                Beståetlist = [dictionary["Bestået"]]
            else:
                Bestået = np.nan

            newdick = dict(zip(newkeys,newvalues))
            if len(newdick) == 0:
                gennemsnit = np.nan
            else:
                gennemsnit = sum([xx*yy for xx,yy in newdick.items()])/sum(newdick.values())

            x8 = sum(Beståetlist) 
            x9 = gennemsnit
            x10 = x_12
            x11 = x_10
            x12 = x_7
            x13 = x_4
            x14 = x_02
            x15 = x_00
            x16 = x_m3
            x17 = Ejmødt
            x18 = Ikkebestået
    
            data = [url,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18]
            df[j+1] = data
        else:
            a = np.empty(20)
            a[:] = np.nan
            df[j+1] = a
      #######################  
        if len(dff) == 5:
            keys = []
            values = []

            #Soft results without tilmeldte and fremmødte
            for i in range(0,len(dff[0][0])):
                keys.append(dff[0][0][i])
                values.append(dff[0][1][i])
            dictionary = dict(zip(keys,values))
            if "Ordinær eksamen" in dictionary:
                del dictionary["Ordinær eksamen"]
            if "Antal tilmeldte" in dictionary:
                del dictionary["Antal tilmeldte"]
            if "Fremmødte" in dictionary:
                del dictionary["Fremmødte"]
            dictionary["Reeksamen"] = "Reeksamen"

            #if "kursus" in dictionary:
            #    x0 = dictionary["kursus"]
            #else:
            #    x0 = np.nan
            if "Fakultet" in dictionary:
                x1 = dictionary["Fakultet"]
            else:
                x1 = np.nan
            if "Institut" in dictionary:
                x2 = dictionary["Institut"]
            else:
                x2 = np.nan
            if "Termin" in dictionary:
                x3 = dictionary["Termin"]
            else:
                x3 = np.nan
            if "ECTS" in dictionary:
                x4 = dictionary["ECTS"]
            else:
                x4 = np.nan    
            x5 = dictionary["Reeksamen"]

            data1 = [x0,x1,x2,x3,x4,x5]

            #HARD RESULTS
            Karakter = []
            Antal = []
            for i in range(0,len(dff[4]["Karakter"])):
                Karakter.append(dff[4]["Karakter"][i])
                Antal.append(dff[4]["Antal"][i])
            dictionary = dict(zip(Karakter,Antal))
            #print("Dictionary: ", dictionary)
            Beståetlist = []

            tolv = 12
            ti = 10
            syv = 7
            fire = 4
            nulto = 2
            nulnul = 0
            minustre = -3
    
            newkeys = []
            newvalues = []
            if "12" in dictionary:
                newkeys.append(tolv)
                newvalues.append(dictionary["12"])
                Beståetlist.append(dictionary["12"])
                x_12 = dictionary["12"]
            elif 12 in dictionary:
                newkeys.append(tolv)
                newvalues.append(dictionary[12])
                Beståetlist.append(dictionary[12])
                x_12 = dictionary[12]
            else:
                x_12 = np.nan
            if "10" in dictionary:
                newkeys.append(ti)
                newvalues.append(dictionary["10"])
                Beståetlist.append(dictionary["10"])
                x_10 = dictionary["10"]
            elif 10 in dictionary:
                newkeys.append(ti)
                newvalues.append(dictionary[10])
                Beståetlist.append(dictionary[10])
                x_10 = dictionary[10]
            else:
                x_10 = np.nan
            if "7" in dictionary:
                newkeys.append(syv)
                newvalues.append(dictionary["7"])
                Beståetlist.append(dictionary["7"])
                x_7 = dictionary["7"]
            elif 7 in dictionary:
                newkeys.append(syv)
                newvalues.append(dictionary[7])
                Beståetlist.append(dictionary[7])
                x_7 = dictionary[7]
            else:
                x_7 = np.nan
            if "4" in dictionary:
                newkeys.append(fire)
                newvalues.append(dictionary["4"])
                Beståetlist.append(dictionary["4"])
                x_4 = dictionary["4"]
            elif 4 in dictionary:
                newkeys.append(fire)
                newvalues.append(dictionary[4])
                Beståetlist.append(dictionary[4])
                x_4 = dictionary[4]
            else:
                x_4 = np.nan
            if "02" in dictionary:
                newkeys.append(nulto)
                newvalues.append(dictionary["02"])
                Beståetlist.append(dictionary["02"])
                x_02 = dictionary["02"]
            elif 2 in dictionary:
                newkeys.append(nulto)
                newvalues.append(dictionary[2])
                Beståetlist.append(dictionary[2])
                x_02 = dictionary[2]
            else:
                x_02 = np.nan
            if "00" in dictionary:
                newkeys.append(nulnul)
                newvalues.append(dictionary["00"])
                x_00 = dictionary["00"]
            elif 0 in dictionary:
                newkeys.append(nulnul)
                newvalues.append(dictionary[0])
                x_00 = dictionary[0]
            else:
                x_00 = np.nan
            if "-3" in dictionary:
                newkeys.append(minustre)
                newvalues.append(dictionary["-3"]) 
                x_m3 = dictionary["-3"]
            elif -3 in dictionary:
                newkeys.append(minustre)
                newvalues.append(dictionary[-3]) 
                x_m3 = dictionary[-3]
            else:
                x_m3 = np.nan
            if "Ej mødt" in dictionary:
                Ejmødt = dictionary["Ej mødt"]
            else:
                Ejmødt = np.nan
            if "Ikke bestået" in dictionary:
                Ikkebestået = dictionary["Ikke bestået"]
            else:
                Ikkebestået = np.nan
            if "Bestået" in dictionary:
                Bestået = dictionary["Bestået"]
                Beståetlist = [dictionary["Bestået"]]
            else:
                Bestået = np.nan

            newdick = dict(zip(newkeys,newvalues))
            #print("Newdick: ", newdick)
        
            if len(newdick) == 0:
                gennemsnit = np.nan
            else:
                gennemsnit = sum([xx*yy for xx,yy in newdick.items()])/sum(newdick.values())

            x6 = sum(dictionary.values())
            if "Ej mødt" in dictionary:
                x7 = sum(dictionary.values())-dictionary["Ej mødt"]
            else:
                x7 = sum(dictionary.values())

            x8 = sum(Beståetlist) 
            x9 = gennemsnit
            x10 = x_12
            x11 = x_10
            x12 = x_7
            x13 = x_4
            x14 = x_02
            x15 = x_00
            x16 = x_m3
            x17 = Ejmødt
            x18 = Ikkebestået

            data = [url, x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18]
            m = j+1
            stringz = "re "+str(m)
            df[stringz] = data

        else:
            m = j+1
            stringz = "re " + str(m)
            a = np.empty(20)
            a[:] = np.nan
            df[stringz] = a
    except Exception as e:
        m = j+1
        stringz = "re " + str(m)
        a = np.empty(20)
        a[:] = np.nan
        df[stringz] = a
        errormessages.append(e)
        errormessages.append(j)
        faultyurls.append(url)
        faultyurls.append(j)
    
df.to_pickle('RESULTATER_28_AUG_AFTEN.pkl')
import numpy as np
np.savetxt("FAULTYURLS_28_AUG_AFTEN.txt",faultyurls,delimiter=",")
np.savetxt("ERRORMESSAGES_28_AUG_AFTEN.txt",errormessages,delimiter=",")

HBox(children=(IntProgress(value=0, max=33443), HTML(value='')))

TypeError: Mismatch between array dtype ('<U72') and format specifier ('%.18e')

In [19]:
import pandas as pd
log_df = pd.read_csv('logPhilip_csv.csv',sep=';') # load the ;-separated log

In [20]:
# Load the LOG
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

log_df

      id;project;connector_type;t;delta_t;url;redirect_url;response_size;response_code;success;error
0      0;grade_scrape;requests;1567022778.6213806;-0....
1      1;grade_scrape;requests;1567022779.7417097;-0....
2      2;grade_scrape;requests;1567022780.7561665;-0....
3      3;grade_scrape;requests;1567022781.7638493;-0....
4      4;grade_scrape;requests;1567022782.7096715;-0....
5      5;grade_scrape;requests;1567022783.669191;-0.2...
6      6;grade_scrape;requests;1567022784.6041164;-0....
7      7;grade_scrape;requests;1567022785.599375;-0.3...
8      8;grade_scrape;requests;1567022786.6667676;-0....
9      9;grade_scrape;requests;1567022787.6874204;-0....
10     10;grade_scrape;requests;1567022788.63848;-0.2...
11     11;grade_scrape;requests;1567022789.619967;-0....
12     12;grade_scrape;requests;1567022790.6279426;-0...
13     13;grade_scrape;requests;1567022791.6349578;-0...
14     14;grade_scrape;requests;1567022792.660766;-0....
15     15;grade_scrape;requests;1567022793.7608979;-0...
16     16;grade_scrape;requests;1567022794.821033;-0....
17     17;grade_scrape;requests;1567022795.9211786;-0...
18     18;grade_scrape;requests;1567022796.9660075;-0...
19     19;grade_scrape;requests;1567022797.977067;-0....
20     20;grade_scrape;requests;1567022798.999005;-0....
21     21;grade_scrape;requests;1567022799.9789941;-0...
22     22;grade_scrape;requests;1567022801.0102558;-0...
23     23;grade_scrape;requests;1567022802.0478325;-0...
24     24;grade_scrape;requests;1567022803.0834732;-0...
25     25;grade_scrape;requests;1567022804.183209;-0....
26     26;grade_scrape;requests;1567022805.2520845;-0...
27     27;grade_scrape;requests;1567022806.302969;-0....
28     28;grade_scrape;requests;1567022807.2763956;-0...
29     29;grade_scrape;requests;1567022808.2399702;-0...
...                                                  ...
33413                                                NaN
33414                                                NaN
33415                                                NaN
33416  33416;grade_scrape;requests;1567057760.624079;...
33417  33417;grade_scrape;requests;1567057761.5961542...
33418  33418;grade_scrape;requests;1567057762.5798318...
33419  33419;grade_scrape;requests;1567057763.569841;...
33420  33420;grade_scrape;requests;1567057764.5337968...
33421  33421;grade_scrape;requests;1567057765.5130773...
33422  33422;grade_scrape;requests;1567057766.4996111...
33423  33423;grade_scrape;requests;1567057767.4840739...
33424  33424;grade_scrape;requests;1567057768.44007;-...
33425  33425;grade_scrape;requests;1567057769.415096;...
33426  33426;grade_scrape;requests;1567057770.3872662...
33427  33427;grade_scrape;requests;1567057771.3381996...
33428  33428;grade_scrape;requests;1567057772.3267107...
33429  33429;grade_scrape;requests;1567057773.2963376...
33430  33430;grade_scrape;requests;1567057774.2795513...
33431  33431;grade_scrape;requests;1567057775.2682476...
33432  33432;grade_scrape;requests;1567057776.242597;...
33433  33433;grade_scrape;requests;1567057777.2243397...
33434  33434;grade_scrape;requests;1567057778.184834;...
33435  33435;grade_scrape;requests;1567057779.192011;...
33436  33436;grade_scrape;requests;1567057780.1615558...
33437  33437;grade_scrape;requests;1567057781.12553;-...
33438  33438;grade_scrape;requests;1567057782.0907547...
33439  33439;grade_scrape;requests;1567057783.066362;...
33440  33440;grade_scrape;requests;1567057784.036437;...
33441  33441;grade_scrape;requests;1567057785.0036025...
33442  33442;grade_scrape;requests;1567057785.9789844...

[33443 rows x 1 columns]

In [13]:
dt = log_df.dt.values[0]

AttributeError: 'DataFrame' object has no attribute 'dt'

In [ ]:
import datetime
# Convert the time column 't' to datetime 
#log_df['dt'] = log_df.t.apply(datetime.datetime.fromtimestamp)
log_df['dt'] = pd.to_datetime(log_df.t,unit='s')

# Plot the time it took to make the call
plt.figure(figsize=(15,4))
plt.plot(log_df.dt,log_df.delta_t)
plt.ylabel('Delta t')
plt.xlabel('Scraping progress')
import datetime

# Plot the response size over time.
plt.figure(figsize=(15,4))
plt.ylabel('Size of response')
plt.xlabel('Scraping progress')
plt.plot(log_df.dt,log_df.response_size)

# Plot the delta_t against the response_size. These two should correlate pretty well.
plt.scatter(log_df.delta_t,log_df.response_size)

## Investigate errors
log_df.success.value_counts() ## Count errors
## Groupby time
# round the time for aggregation
log_df['dt_minute'] = log_df.dt.apply(lambda x: x-datetime.timedelta(seconds=x.second,microseconds=x.microsecond))
log_df['dt_hour'] = log_df.dt.apply(lambda x: x-datetime.timedelta(minutes=x.minute,seconds=x.second,microseconds=x.microsecond))
log_df.groupby('dt_hour').success.mean()