In [52]:
import scraping_class
logfile = 'log.txt'## name your log file.
connector = scraping_class.Connector(logfile)
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm_notebook

In [53]:
import pandas as pd
import numpy as np
import html5lib
import sys
import pickle
from tqdm import tqdm_notebook

In [54]:
with open('df_final.pkl', 'rb') as f:
    df = pickle.load(f)

## Defining function to look into statistics

In [101]:
def tlen(name):
    tlen = pd.DataFrame()
    tlen_id = []
    tlen_value = []
    tlen_share = []
    for i in df[name].unique():
        tlen_id.append(i)
        tlen_value.append(len(df.loc[df[name] == i]))
        
    for i in df[name].unique():
        tlen_share.append((len(df.loc[df[name] == i])/sum(tlen_value)*100))
        
    tlen_id.append('Total')
    tlen_value.append(sum(tlen_value))
    tlen_share.append(sum(tlen_share))
        
        
    tlen['Id'] = tlen_id
    tlen['Value'] = tlen_value
    tlen['Share %'] = tlen_share
        
    return(tlen.sort_values('Value',ascending=True))

In [102]:
def tlen_year(name,year):
    df1 = df[df['Year'] == year]
    tlen = pd.DataFrame()
    tlen_id = []
    tlen_value = []
    tlen_share = []
    for i in df[name].unique():
        tlen_id.append(i)
        tlen_value.append(len(df1.loc[df[name] == i]))
    
    for i in df[name].unique():
        tlen_share.append((len(df1.loc[df[name] == i])/sum(tlen_value)*100))
        
    tlen_id.append('Total')
    tlen_value.append(sum(tlen_value))
    tlen_share.append(sum(tlen_share))
        
    tlen['Id'] = tlen_id
    tlen['Value'] = tlen_value
    tlen['Share %'] = tlen_share
        
    return(tlen.sort_values('Value',ascending=True))

In [ ]:
def tlen_byyear(name):
    
    tlen = pd.DataFrame()
    my_dict = {}
    for i in df[name].unique():
        my_dict['Id'] = i
        for k in df['Year'].unique():
            my_dict
        
        df1 = df[df['Year'] == '2013-2014']
        tlen_1314.append(len(df1.loc[df[name] == i]))
        df2 = df[df['Year'] == '2014-2015']
        tlen_1415.append(len(df2.loc[df[name] == i]))
        df3 = df[df['Year'] == '2015-2016']
        tlen_1516.append(len(df3.loc[df[name] == i]))
        df4 = df[df['Year'] == '2016-2017']
        tlen_1617.append(len(df4.loc[df[name] == i]))
        df5 = df[df['Year'] == '2017-2018']
        tlen_1718.append(len(df5.loc[df[name] == i]))
    
    
        
    tlen_id.append('Total')
    tlen_value.append(sum(tlen_value))
    tlen_share.append(sum(tlen_share))
        
    tlen['Id'] = tlen_id
    tlen[''2013-2014''] = tlen_value
    tlen['Share %'] = tlen_share
        
    return(tlen.sort_values('Value',ascending=True))

In [150]:
def tlen_byyear(name):
    
    tlen = pd.DataFrame()
    tlen_id = []
    tlen_1314 = []
    tlen_1415 = []
    tlen_1516 = []
    tlen_1617 = []
    tlen_1718 = []

    for i in df[name].unique():
        tlen_id.append(i)
        df1 = df[df['Year'] == '2013-2014']
        tlen_1314.append(len(df1.loc[df[name] == i]))
        df2 = df[df['Year'] == '2014-2015']
        tlen_1415.append(len(df2.loc[df[name] == i]))
        df3 = df[df['Year'] == '2015-2016']
        tlen_1516.append(len(df3.loc[df[name] == i]))
        df4 = df[df['Year'] == '2016-2017']
        tlen_1617.append(len(df4.loc[df[name] == i]))
        df5 = df[df['Year'] == '2017-2018']
        tlen_1718.append(len(df5.loc[df[name] == i]))
    
    
        
    tlen_id.append('Total')
    tlen_1314.append(sum(tlen_1314))
    tlen_1415.append(sum(tlen_1415))
    tlen_1516.append(sum(tlen_1516))
    tlen_1617.append(sum(tlen_1617))
    tlen_1718.append(sum(tlen_1718))
    
        
    tlen['Id'] = tlen_id
    tlen['2013-2014'] = tlen_1314
    tlen['2014-2015'] = tlen_1415
    tlen['2015-2016'] = tlen_1516
    tlen['2016-2017'] = tlen_1617
    tlen['2017-2018'] = tlen_1718
        
    return(tlen)

# Descriptive statistic - diving in to the weirds of the data
## Years
It is seen from `tlen('year')` that there a many fewer eksamns in the study year 2013-2014 than the rest. By looking at `tlen_year('Termin','2013-2014')` it is seen that only the summer eksamns are in this year. By going to the grade web-page it is seen that it only tracks data to summer 14, and therefore eksamns from winter 13 not included.

It is seen that apparently 2015-2016 has around 500 more eksamns than both the year before and the year after. Most of them are from HUM as seen in `tlen_byyear('Fakultet')`. F.eks. TORS has 150 in 2015-2016 and suddenly 1 in 2016-2017. It seems like 2015-2016 as seen by `tlen_byyear('Institut')` maybe there where an extra focus on doing statistics in 2016-2017. This hypothesis is backed up by `tlen_byyear('Censorship form_edit')` where the rise is shown in nan. I.E the courses where the info on the exam is limited.

An Interesting fact from `tlen_byyear('Censorship form_edit')` is that no external is rising whil external is falling.

In [200]:
tlen_byyear('Institut')

,Id,2013-2014,2014-2015,2015-2016,2016-2017,2017-2018
0,Niels Bohr Institutet,58,125,131,124,131
1,Institut for Statskundskab,64,101,165,156,153
2,Statens Naturhistoriske Museum,9,28,22,27,25
3,Institut for Geovidenskab og Naturforvaltning,98,223,225,233,236
4,"Institut for Medier, Erkendelse og Formidling",47,94,123,105,54
5,"Saxo-Instituttet - Ark√¶ologi, Etnologi, Histor...",34,45,74,33,40
6,"Institut for Engelsk, Germansk og Romansk",19,69,181,139,113
7,√òkonomisk Institut,84,167,184,166,126
8,Datalogisk Institut,32,79,69,76,75
9,Institut for Plante- og Milj√∏videnskab,43,81,88,85,90
10,MSc Animal Science,3,13,16,13,14
11,Biologisk Institut,70,146,151,151,150
12,MSc Immunologi og inflammation,0,0,0,7,10
13,Uddannelsesr√•d for veterin√¶rvidenskab og husdy...,6,42,38,24,21
14,Institut for F√∏devarevidenskab,23,46,51,54,55
15,Institut for F√∏devare- og Ressource√∏konomi,42,82,103,92,92
16,Institut for antropologi,8,45,73,55,61
17,Kemisk Institut,39,95,94,89,91
18,Sociologisk Institut,30,64,32,35,69
19,Institut for Naturfagenes Didaktik,6,9,11,15,10
20,MSc L√¶gemiddelvidenskab,11,42,26,24,15
21,Folkesundhedsvidenskab,10,37,47,43,39
22,NaN,0,0,0,0,0
23,Den Sundhedsfaglige supplerings- og kandidatud...,10,20,26,27,26
24,Master i Public Health (MA),3,10,15,13,10
25,Institut for Idr√¶t og Ern√¶ring,36,94,89,82,85
26,Farmaci,22,64,45,46,37
27,Institut for Matematiske Fag,63,153,171,157,167
28,MSc Humanbiologi,4,11,9,18,12
29,Studien√¶vnet for Global Udvikling,0,7,9,9,8
30,Global Sundhed,3,10,16,14,18
31,Studien√¶vnet for Afrikastudier,1,6,12,9,11
32,Institut for Tv√¶rkulturelle og regionale studier,29,49,154,1,0
33,Institut for Kunst og Kulturvidenskab,37,66,93,44,28
34,Institut for Nordiske Studier og Sprogvidenskab,33,55,83,3,0
35,Medicin,70,158,163,195,224
36,Veterin√¶rmedicin,51,113,76,76,67
37,Institut for Psykologi,39,72,71,76,96
38,Odontologi,24,54,76,73,74
39,IVA,13,43,50,16,9
40,Masteruddannelse i l√¶gemiddelregistrering,0,0,0,8,15
41,Institut for Farmaci,0,1,2,4,3
42,Molekyl√¶r biomedicin,7,25,19,17,15
43,Institut for L√¶gemiddeldesign og Farmakologi,2,2,4,3,4
44,Institut for Klinisk Veterin√¶r- og Husdyrsvide...,1,2,6,4,7
45,Master of Disaster Management (MA),0,6,7,7,10
46,IT og sundhed,5,17,19,20,16
47,Juridisk Diplomuddannelse i Krimonologi,0,0,1,6,3
48,Institut for Veterin√¶r Sygdomsbiologi,0,1,1,1,1
49,Medicin og teknologi,6,17,23,27,30
50,Milj√∏kemi og sundhed,0,1,1,1,2
51,Masteruddannelse i hovedpinesygdomme,0,0,0,4,1
52,Master i International Health (MA),0,3,2,2,0
53,Juridisk Masteruddannelse i Konfliktm√¶gling,0,0,1,1,1
54,Institut for Produktionsdyr og Heste,0,2,0,0,0
55,Total,1195,2695,3148,2710,2650

In [201]:
tlen_byyear('Censorship form_edit')

,Id,2013-2014,2014-2015,2015-2016,2016-2017,2017-2018
0,No external censorship,603,1448,1598,1664,1814
1,External censorship,547,1245,1295,1120,993
2,nan,196,347,634,285,195
3,Total,1346,3040,3527,3069,3002

In [192]:
list_1 = df[df['Year'] == '2014-2015']['ID'].to_list()
list_2 = df[df['Year'] == '2015-2016']['ID'].to_list()
list_3 = df[df['Year'] == '2016-2017']['ID'].to_list()
list_4 = df[df['Year'] == '2017-2018']['ID'].to_list()

list_5 = []
for i in list_3:
    if i not in list_4:
        list_5.append(i)

len(list_5)

907

In [165]:
tlen_byyear('Kursus')

KeyboardInterrupt:

In [164]:
for i in range(len(df['Year'])):
    if df['Year'][i] == '2014-2015':

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [139]:
tlen_year('Fakultet','2014-2015')

                                         Id  Value     Share %
5                   Det Teologiske Fakultet     82    2.697368
4                    Det Juridiske Fakultet    269    8.848684
2                 Det Humanistiske Fakultet    421   13.848684
1       Det Samfundsvidenskabelige Fakultet    456   15.000000
3       Det Sundhedsvidenskabelige Fakultet    651   21.414474
0  Det Natur- og Biovidenskabelige Fakultet   1161   38.190789
6                                     Total   3040  100.000000

In [15]:
print(df.columns.values)

['Kursus' 'Fakultet' 'Institut' 'Termin' 'ECTS' 'Eksamenstype'
 'Antal tilmeldte' 'Fremm√∏dte' 'Antal best√•et' 'Eksamensgennemsnit' 12 10
 7 4 2 0 -3 'Ej m√∏dt' 'Ikke best√•et' 'Year' 'ID' 'Re-exam_dummy' 'URL_E'
 'level_0' 'Course Name' 'Credit' 'Type of assessment' 'Aid'
 'Marking scale' 'Censorship form' 'Exam period' 'Re-exam' 'Language'
 'Course code' 'Level' 'Duration' 'Placement' 'Schedule' 'Study board'
 'Course id' 'Category' 'Lectures' 'Preparation' 'Exam' 'Total' 'Content'
 'Learning\r\nOutcome' 'Class Instruction' 'Practical exercises'
 'Exam registration requirements' 'Field Work' 'Course capacity' 'Seminar'
 'Guidance' 'Continuing and further education' 'Price' 'Class Seminar'
 'Class Exercises' 'Study Groups' 'Exercises' 'Exam Preparation'
 'Excursions' '√òvelseshold' '√òvelser' 'Course Preparation'
 'Theory exercises' 'Project work' 'Clinical practice' 'Praktik'
 'Colloquia' 'Laboratory' 'E-Learning' 'Practical Training' 'Praksishold'
 'Tutoring' 'Manuduktion' 'Aid_edit' 'Marking scale_edit'
 'Censorship form_edit' 'Bachelor' 'Bachelor choice'
 'Full Degree Master choice' 'Full Degree Master' 'Propaedeutics'
 'Part Time Master' 'Ph.D.' 'Professionsbachelor' 'Master' 'Duration_edit'
 'Credit_edit' 'Lectures_edit' 'Preparation_edit' 'Exam_edit' 'Total_edit'
 'Practical exercises_edit' 'Field Work_edit' 'Guidance_edit'
 'Class Seminar_edit' 'Class Exercises_edit' 'Study Groups_edit'
 'Exercises_edit' 'Exam Preparation_edit' 'Excursions_edit'
 '√òvelseshold_edit' '√òvelser_edit' 'Course Preparation_edit'
 'Theory exercises_edit' 'Project work_edit' 'Clinical practice_edit'
 'Praktik_edit' 'Colloquia_edit' 'Laboratory_edit' 'E-Learning_edit'
 'Practical Training_edit' 'Praksishold_edit' 'Tutoring_edit'
 'Manuduktion_edit' 'Language_edit' 'Type of assessmet_edit' 'URL_C']

In [44]:
pd.to_numeric(df['Antal tilmeldte']).describe()

count    13984.000000
mean        47.915618
std         73.119560
min          4.000000
25%         12.000000
50%         24.000000
75%         49.000000
max        773.000000
Name: Antal tilmeldte, dtype: float64

In [42]:
tlen('Termin' )

        Id  Value
3      v15   1153
14     s16    985
2      v16    917
4      v14    913
21     v17    895
16     s15    851
15     s14    761
13     s17    755
1      s18    699
22  v17/B1    394
23  v16/B1    391
24  v15/B1    385
7   v14/B1    354
17  v17/B2    343
25  v16/B2    337
27  s16/B3    333
29  s18/B3    332
26  v15/B2    325
30  s17/B3    322
6   v14/B2    309
0   s15/B3    306
31  s14/B3    293
18  s17/B4    260
28  s18/B4    259
19  s16/B4    256
5   s15/B4    256
20  s14/B4    241
10  s16/B5     87
9   s17/B5     85
8   s18/B5     80
12  s14/B5     50
11  s15/B5     50
32  s16/B2      2
35  v16/B4      2
33  s15/B2      1
34  s14/B2      1
36  v15/B4      1

In [49]:
tlen('Year')

          Id  Value
0  2013-2014   1346

In [50]:
tlen('Fakultet')

                                         Id  Value
0  Det Natur- og Biovidenskabelige Fakultet    519
3       Det Sundhedsvidenskabelige Fakultet    238
2       Det Samfundsvidenskabelige Fakultet    225
1                 Det Humanistiske Fakultet    212
5                    Det Juridiske Fakultet    117
4                   Det Teologiske Fakultet     35

In [41]:
len(tlen('Institut'))
tlen('Institut')

                                                   Id  Value
3       Institut for Geovidenskab og Naturforvaltning   1015
35                                            Medicin    810
7                                  √òkonomisk Institut    727
27                       Institut for Matematiske Fag    711
11                                 Biologisk Institut    668
1                          Institut for Statskundskab    639
0                               Niels Bohr Institutet    569
6           Institut for Engelsk, Germansk og Romansk    521
4       Institut for Medier, Erkendelse og Formidling    423
15         Institut for F√∏devare- og Ressource√∏konomi    411
17                                    Kemisk Institut    408
9              Institut for Plante- og Milj√∏videnskab    387
25                     Institut for Idr√¶t og Ern√¶ring    386
36                                   Veterin√¶rmedicin    383
37                             Institut for Psykologi    354
8                                 Datalogisk Institut    331
38                                         Odontologi    301
33              Institut for Kunst og Kulturvidenskab    268
16                           Institut for antropologi    242
32   Institut for Tv√¶rkulturelle og regionale studier    233
18                               Sociologisk Institut    230
14                     Institut for F√∏devarevidenskab    229
5   Saxo-Instituttet - Ark√¶ologi, Etnologi, Histor...    226
26                                            Farmaci    214
21                             Folkesundhedsvidenskab    176
34    Institut for Nordiske Studier og Sprogvidenskab    174
39                                                IVA    131
13  Uddannelsesr√•d for veterin√¶rvidenskab og husdy...    131
20                            MSc L√¶gemiddelvidenskab    118
2                      Statens Naturhistoriske Museum    111
23  Den Sundhedsfaglige supplerings- og kandidatud...    109
49                               Medicin og teknologi    103
42                               Molekyl√¶r biomedicin     83
46                                      IT og sundhed     77
30                                     Global Sundhed     61
10                                 MSc Animal Science     59
28                                   MSc Humanbiologi     54
24                        Master i Public Health (MA)     51
19                 Institut for Naturfagenes Didaktik     51
31                     Studien√¶vnet for Afrikastudier     39
29                  Studien√¶vnet for Global Udvikling     33
45                 Master of Disaster Management (MA)     30
40          Masteruddannelse i l√¶gemiddelregistrering     23
44  Institut for Klinisk Veterin√¶r- og Husdyrsvide...     20
12                     MSc Immunologi og inflammation     17
43       Institut for L√¶gemiddeldesign og Farmakologi     15
41                               Institut for Farmaci     10
47            Juridisk Diplomuddannelse i Krimonologi     10
52                 Master i International Health (MA)      7
50                               Milj√∏kemi og sundhed      5
51               Masteruddannelse i hovedpinesygdomme      5
48              Institut for Veterin√¶r Sygdomsbiologi      4
53        Juridisk Masteruddannelse i Konfliktm√¶gling      3
54               Institut for Produktionsdyr og Heste      2
22                                                NaN      0

In [38]:
pd.to_numeric(df['Eksamensgennemsnit']).describe()

count    11974.000000
mean         6.939119
std          2.289251
min         -3.000000
25%          5.533333
50%          7.250000
75%          8.625000
max         12.000000
Name: Eksamensgennemsnit, dtype: float64

In [117]:
with open('df_final_outer-Copy1.pkl', 'rb') as f:
    dfo = pickle.load(f)

In [122]:
dfo[dfo['Year'] == '2013-2014']

,Kursus,Fakultet,Institut,Termin,ECTS,Eksamenstype,Antal tilmeldte,Fremm√∏dte,Antal best√•et,Eksamensgennemsnit,...,Colloquia_edit,Laboratory_edit,E-Learning_edit,Practical Training_edit,Praksishold_edit,Tutoring_edit,Manuduktion_edit,Language_edit,Type of assessmet_edit,URL_C
21,¬ß3 i praksis - Naturbeskyttelsesloven,Det Natur- og Biovidenskabelige Fakultet,Institut for Geovidenskab og Naturforvaltning,s14/B5,5,Ordin√¶r eksamen,12,12,12,9.16667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Portfolio,https://kurser.ku.dk/archive/2013-2014/course/...
27,1. √•rsprojekt,Det Sundhedsvidenskabelige Fakultet,Folkesundhedsvidenskab,s14,15,Ordin√¶r eksamen,59,59,59,9.40678,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,1.√•rsprojekt,Det Humanistiske Fakultet,"Institut for Medier, Erkendelse og Formidling",s14,75,Ordin√¶r eksamen,64,60,60,7.16667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,20. √•rhundredes filosofi,Det Humanistiske Fakultet,"Institut for Medier, Erkendelse og Formidling",s14,15,Ordin√¶r eksamen,69,67,59,6.08955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,306. Masterprojekt,Det Humanistiske Fakultet,"Institut for Medier, Erkendelse og Formidling",s14,15,Ordin√¶r eksamen,9,9,9,9.44444,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,5. CCP1 Danish Culture,Det Humanistiske Fakultet,"Saxo-Instituttet - Ark√¶ologi, Etnologi, Histor...",s14,75,Ordin√¶r eksamen,97,97,89,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,6. CCP2 Danish Culture,Det Humanistiske Fakultet,"Saxo-Instituttet - Ark√¶ologi, Etnologi, Histor...",s14,75,Ordin√¶r eksamen,45,39,37,8.66667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,7. CCP3 Danish Culture,Det Humanistiske Fakultet,"Saxo-Instituttet - Ark√¶ologi, Etnologi, Histor...",s14,15,Ordin√¶r eksamen,11,10,10,10.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,8. CCP4A Intensive Course in Danish Culture,Det Humanistiske Fakultet,"Saxo-Instituttet - Ark√¶ologi, Etnologi, Histor...",s14,15,Ordin√¶r eksamen,37,31,27,7.58065,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
44,8. CCP4C Intensive Course in Danish Culture,Det Humanistiske Fakultet,"Saxo-Instituttet - Ark√¶ologi, Etnologi, Histor...",s14,15,Ordin√¶r eksamen,45,44,44,9.75,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
45,8. CCP4D Intensive Course in Danish Culture,Det Humanistiske Fakultet,"Saxo-Instituttet - Ark√¶ologi, Etnologi, Histor...",s14,15,Ordin√¶r eksamen,39,33,26,6.93939,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
46,8. CCP4D Intensive Course in Danish Culture,Det Humanistiske Fakultet,"Saxo-Instituttet - Ark√¶ologi, Etnologi, Histor...",s14,15,Reeksamen,6,5,4,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
47,9. CCP4B Intensive Course in Danish Culture,Det Humanistiske Fakultet,"Saxo-Instituttet - Ark√¶ologi, Etnologi, Histor...",s14,15,Ordin√¶r eksamen,41,34,31,8.97059,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
59,Academic English,Det Humanistiske Fakultet,"Institut for Engelsk, Germansk og Romansk",s14,15,Ordin√¶r eksamen,16,12,12,8.83333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Portfolio,https://kurser.ku.dk/archive/2013-2014/course/...
81,Acceptance and Commitment Ther-apy (ACT),Det Samfundsvidenskabelige Fakultet,Institut for Psykologi,s14/B5,5,Ordin√¶r eksamen,12,12,12,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,Acquisition and Processing of Seismic Data,Det Natur- og Biovidenskabelige Fakultet,Institut for Geovidenskab og Naturforvaltning,s14/B4,75,Ordin√¶r eksamen,16,13,13,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
89,Adf√¶rdsdesign og Offentlige Beslutningsprocess...,Det Samfundsvidenskabelige Fakultet,Institut for Statskundskab,s14,10,Ordin√¶r eksamen,17,16,16,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
115,Adv. Development Economics - Micro Aspects,Det Samfundsvidenskabelige Fakultet,√òkonomisk Institut,s14,75,Ordin√¶r eksamen,29,25,20,6.96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,Adv. Development Economics - Micro Aspects,Det Samfundsvidenskabelige Fakultet,√òkonomisk Institut,s14,75,Reeksamen,7,5,5,8.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,Advanced Algorithms and Data Structures,Det Natur- og Biovidenskabelige Fakultet,Datalogisk Institut,s14/B4,75,Ordin√¶r eksamen,69,45,39,7.68889,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Oral,https://kurser.ku.dk/archive/2013-2014/course/...
138,Advanced Algorithms and Data Structures,Det Natur- og Biovidenskabelige Fakultet,Datalogisk Institut,s14/B4,75,Reeksamen,10,7,6,5.14286,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Oral,https://kurser.ku.dk/archive/2013-2014/course/...
151,Advanced Animal Production Science,Det Sundhedsvidenskabelige Fakultet,MSc Animal Science,s14/B4,15,Ordin√¶r eksamen,6,6,6,11.3333,...,75.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
170,Advanced Biotechnology and Intellectual Proper...,Det Sundhedsvidenskabelige Fakultet,Uddannelsesr√•d for veterin√¶rvidenskab og husdy...,s14/B4,15,Ordin√¶r eksamen,59,59,58,9.52542,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Oral,https://kurser.ku.dk/archive/2013-2014/course/...
171,Advanced Biotechnology and Intellectual Proper...,Det Sundhedsvidenskabelige Fakultet,Uddannelsesr√•d for veterin√¶rvidenskab og husdy...,s14,15,Ordin√¶r eksamen,59,59,58,9.52542,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Oral,https://kurser.ku.dk/archive/2013-2014/course/...
194,Advanced Conflict Management,Det Natur- og Biovidenskabelige Fakultet,Institut for F√∏devare- og Ressource√∏konomi,s14/B4,75,Ordin√¶r eksamen,10,9,9,10.3333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Oral,https://kurser.ku.dk/archive/2013-2014/course/...
257,Advanced Food Chemistry,Det Natur- og Biovidenskabelige Fakultet,Institut for F√∏devarevidenskab,s14/B4,75,Ordin√¶r eksamen,15,12,12,8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Oral,https://kurser.ku.dk/archive/2013-2014/course/...
263,Advanced Health Promotion and Disease Prevention,Det Sundhedsvidenskabelige Fakultet,Den Sundhedsfaglige supplerings- og kandidatud...,s14,75,Ordin√¶r eksamen,9,9,9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,Advanced Health Promotion and Disease Prevention,Det Sundhedsvidenskabelige Fakultet,Master i Public Health (MA),s14,75,Ordin√¶r eksamen,6,6,4,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Course participation written,https://kurser.ku.dk/archive/2013-2014/course/...
278,Advanced Inorganic Chemistry,Det Natur- og Biovidenskabelige Fakultet,Kemisk Institut,s14/B3,75,Ordin√¶r eksamen,20,17,16,8.76471,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Oral,https://kurser.ku.dk/archive/2013-2014/course/...
310,Advanced language processing,Det Natur- og Biovidenskabelige Fakultet,Datalogisk Institut,s14/B3,75,Ordin√¶r eksamen,10,4,4,7,...,15.0,0.0,0.0,0.0,0.0,0.0,0.0,English,Oral,https://kurser.ku.dk/archive/2013-2014/course/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Oral,https://kurser.ku.dk/archive/2013-2014/course/...
28434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28447,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28451,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Course participation not written,https://kurser.ku.dk/archive/2013-2014/course/...
28452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Other,https://kurser.ku.dk/archive/2013-2014/course/...
28455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...
28461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Danish,Written not under invigilation,https://kurser.ku.dk/archive/2013-2014/course/...

In [161]:
dfo[dfo['URL_E'] == 'http://karakterstatistik.stads.ku.dk/Histogram/HEEK03471E/Summer-2018' ][]

,Kursus,Fakultet,Institut,Termin,ECTS,Eksamenstype,Antal tilmeldte,Fremm√∏dte,Antal best√•et,Eksamensgennemsnit,...,Colloquia_edit,Laboratory_edit,E-Learning_edit,Practical Training_edit,Praksishold_edit,Tutoring_edit,Manuduktion_edit,Language_edit,Type of assessmet_edit,URL_C
13307,Kultur og historie,Det Humanistiske Fakultet,"Saxo-Instituttet - Ark√¶ologi, Etnologi, Histor...",s18,15,Ordin√¶r eksamen,19,17,15,8.70588,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN